name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install GRASS GIS
      run: |
        sudo add-apt-repository --yes ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install --yes grass grass-dev
    - name: Test GRASS GIS
      run: |
        grass --tmp-location XY --exec g.version -e
