name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install GRASS GIS
      run: |
        sudo add-apt-repository --yes ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install --yes grass grass-dev
    - name: Test GRASS GIS
      run: |
        grass --tmp-location XY --exec g.version -e
    - name: Cache sample data
      id: cache-nc_spm_08_grass7
      uses: actions/cache@v1
      with:
        path: nc_spm_08_grass7
        key: ${{ runner.os }}-nc_spm_08_grass7
    - name: Get sample data
      if: steps.cache-nc_spm_08_grass7.outputs.cache-hit != 'true'
      run: |
        grass --tmp-location XY --exec g.extension g.download.location --verbose
        grass --tmp-location XY --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz dbase=. --verbose
    - name: Test structure of Python files
      run: |
        python3 ./tests/functions_format.py
    - name: Test execution of Python files
      run: |
        python3 ./tests/functions.py
    - name: Test structure of JSON files
      run: |
        python3 ./tests/json_structure.py
